# see https://docs.docker.com/compose/compose-file/compose-versioning/
version: "3.5" # specify docker-compose version, v3.5 is compatible with docker 17.12.0+

# Define the services/containers to be run
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  mongodb:
    container_name: mongo
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

  client:
    container_name: client
    restart: always
    build: ./client
    environment:
      - "BACKEND_API_URL=http://api:8080"
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - frontend
      - backend

  api:
    container_name: server
    restart: always
    build: ./server
    environment:
      - "SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/blog"
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - backend

volumes:
  mongodata:
#    driver: local-persist
#    driver_opts:
#      mountpoint: ./data

networks:
  frontend:
  backend:
