FROM openjdk:17-jdk-alpine
MAINTAINER Sandip
COPY target/spring-reactive-post-server-1.0.0-SNAPSHOT.jar spring-reactive-post-server-1.0.0-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/spring-reactive-post-server-1.0.0-SNAPSHOT.jar"]